### ISSUE TITLE
Log messages to show time first

### ISSUE THREAD

**Issue by arnatal** [CloudNativeSDWAN/egress-watcher#10]
Right now the watcher shows the time in the logs in the middle of the log message. Like in this example:

`{"level":"info","event-handler":"Create","hosts":["kubecon.cisco.com"],"time":"2022-05-10T13:33:33Z","message":"reconciling service entry..."}`

It would be interesting to move the time to be the first thing to show, that would help finding relevant log messages faster and  grouping log messages that are part of the same event.

**Comment by asimpleidea** [comment]
This is due to formatted logging: we use `zerolog` for logs and using json format is way faster and useful for bots/tracers/programs as they just care about the fields and not the order or pretty printing.

But I agree that for humans this is not readable at all. So I will change this to detect your verbosity level: if it is `0` (or also `1`, but I would prefer `0` because it is usually associated to debug, so for us humans) it means that you want to know exactly what's happening and the log will be in a slower but very human readable format:

`3:04PM INF Hello World foo=bar`
